name: tests

on:
  push:
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [^10.0, ^11.0]
        exclude:
          # # Exclude laravel 11 on php 8.1 as it requires php 8.2+
          - php: 8.1
            laravel: ^11.0
          # # Exclude laravel 9 on php 7.2, 7.3 and 7.4 as it requires php 8.0+
          # - php: 7.2
          #   laravel: ^9.0
          # - php: 7.4
          #   laravel: ^9.0

    name: Run Test (P${{ matrix.php }} - L${{ matrix.laravel }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
           composer require "illuminate/database=${{ matrix.laravel }}" --no-update
           composer update --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: vendor/bin/phpunit --verbose --testdox

      - name: Upload artifacts (on failure)
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
          
